production-sqlite:
  adapter: sqlite3
  database: db/alminium.sqlite3

production:
  adapter: mysql2
  database: alminium
  host: <%= ENV['ALM_DB_HOST'] || 'localhost' %>
  username: alminium
  password: alminium
  encoding: utf8
